### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by harshvardhansharma** [KIZUNACOIN/kizunacoin-headless#2]
```Error: known bad ET2dbWJU6jP4D6ALMXJxsaVGg0biG9hV2dhEOVaPFyE=: src output must be before last ball```

**Comment by cryptoinhero** [comment]
Please go to ./node_modules
In the core directory you would see constants.js.
https://explorer.kizunacoin.jp/#ET2dbWJU6jP4D6ALMXJxsaVGg0biG9hV2dhEOVaPFyE=
this transaction level is 1100.
So please try to change  exports.spendUnconfirmedUpgradeMci = exports.bTestnet ? 589000 : 100000;
100000 to 1000, please update this parameter.

**Comment by harshvardhansharma** [comment]
tried. not working.
when I remove the db files, the node starts syncing but soon looses peers at around 1100 mci

**Comment by cryptoinhero** [comment]
I think you did not remove the db.
Please remove the db first.
And then please try again.

**Comment by harshvardhansharma** [comment]
thanks, node syncing now.
